# MCP Gateway 自定义服务器配置示例
# 此配置使用 Gateway 自己的服务器配置，而不是 Spring AI 的默认配置

server:
  port: 8080

spring:
  application:
    name: mcp-gateway

  # Spring AI MCP Server 基础配置（仅用于兼容性）
  ai:
    mcp:
      server:
        name: mcp-gateway
        version: 1.0.0
        type: ASYNC
        # 基础 SSE 端点配置（Gateway 会在此基础上添加自己的端点）
        sse-endpoint: /sse
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
    alibaba:
      mcp:
        gateway:
          enabled: true
          registry: nacos
          # SSE 服务器配置
          sse:
            enabled: true
            endpoint: /sse
            protocol-version: "2025-03-26"
          # Streamable HTTP 服务器配置
          streamable:
            enabled: true
            endpoint: /streamable
            protocol-version: "2025-06-18"
        nacos:
          serverAddr: localhost:8848
          namespace: public
          username: nacos
          password: nacos

# 日志配置
logging:
  level:
    com.alibaba.cloud.ai.mcp.gateway: DEBUG
    com.alibaba.cloud.ai.autoconfigure.mcp.gateway: DEBUG
    org.springframework.ai: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
# 说明：
# 1. Gateway 使用自己的服务器配置，而不是 Spring AI 的默认配置
# 2. SSE 协议端点: http://localhost:8080/sse
# 3. Streamable HTTP 协议端点: http://localhost:8080/streamable
# 4. 两种协议都支持工具调用、资源管理、提示处理、补全功能
# 5. 可以通过配置独立启用/禁用每种协议
# 6. 可以自定义端点路径和协议版本
