export const pluginEmums = [
  // ========= 示例 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Example",
    childrenClass: "Playground",
    title: "Spring AI Alibaba Playground",
    desc: "一个包含互动对话 UI 的综合示例，体验对话记忆、工具调用、图片生成等。",
    link: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-playground",
    example: "",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Example",
    childrenClass: "MCP",
    title: "MCP 示例",
    desc: "包含如何发布 MCP server、如何发起 MCP 调用的相关示例。",
    link: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    example: "",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Example",
    childrenClass: "文生文聊天",
    title: "ChatClient",
    desc: "在应用中集成 ChatClient 与 ChatModel 的基本使用示例。",
    link: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-chat-example",
    example: "",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Example",
    childrenClass: "文生文聊天",
    title: "同时使用多个模型",
    desc: "在应用中同时声明多个 ChatModel、ChatClient 调用多个模型。",
    link: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-more-platform-and-model-example",
    example: "",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Example",
    childrenClass: "文生图",
    title: "ImageModel",
    desc: "如何使用 ImageModel 集成 Dashscope 模型生成图像。",
    link: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-image-example",
    example: "",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Example",
    childrenClass: "多模态",
    title: "多模态",
    desc: "在与模型的交互中，使用 ChatClient 同时输入文字、图片和视频。",
    link: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-multi-model-example",
    example: "",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Example",
    childrenClass: "ToolCalling",
    title: "百度翻译",
    desc: "在模型调用中使用百度翻译工具实现自然语言翻译，比如中译英。",
    link: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-tool-calling-example",
    example: "",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Example",
    childrenClass: "RAG",
    title: "百炼RAG知识库",
    desc: "通过 Spring AI Alibaba 集成百炼知识库实现 RAG 知识库增强。",
    link: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-rag-example/bailian-rag-knowledge",
    example: "",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Example",
    childrenClass: "RAG",
    title: "模块化RAG",
    desc: "Spring AI 模块化 RAG 的接口定义与基本使用，包括问题重写、检索重排等。",
    link: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-rag-example/module-rag",
    example: "",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Example",
    childrenClass: "可观测",
    title: "可观测",
    desc: "Spring AI Alibaba 集成 AI 可观测系统的使用方法与最佳实践，包括 Metrics、Tracing 等。",
    link: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-observability-example",
    example: "",
    rely: "",
  },
  // ========= 插件 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Tool Calling",
    childrenClass: "搜索",
    title: "百度搜索",
    desc: "借助百度引擎执行网页搜索并获取搜索结果。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/tool-calls/spring-ai-alibaba-starter-tool-calling-baidusearch",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-tool-calling-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-tool-calling-baidusearch</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Tool Calling",
    childrenClass: "搜索",
    title: "微软Bing搜索",
    desc: "借助Bing引擎执行网页搜索并获取搜索结果。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/tool-calls/spring-ai-alibaba-starter-tool-calling-bingsearch",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-tool-calling-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-tool-calling-bingsearch</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Tool Calling",
    childrenClass: "搜索",
    title: "SERP API",
    desc: "借助 SerpAPI 调用搜索引擎并获得搜索结果，支持结果的抓取与分析。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/tool-calls/spring-ai-alibaba-starter-tool-calling-serpapi",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-tool-calling-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-tool-calling-serpapi</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Tool Calling",
    childrenClass: "生产效率",
    title: "阿里翻译",
    desc: "阿里巴巴翻译服务，支持多语言互译。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/tool-calls/spring-ai-alibaba-starter-tool-calling-alitranslate",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-tool-calling-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-tool-calling-alitranslate</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Tool Calling",
    childrenClass: "生产效率",
    title: "谷歌翻译",
    desc: "Google Translate API，提供高质量的翻译服务。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/tool-calls/spring-ai-alibaba-starter-tool-calling-googletranslate",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-tool-calling-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-tool-calling-googletranslate</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Tool Calling",
    childrenClass: "生产效率",
    title: "微软翻译",
    desc: "调用微软翻译API，支持多语言翻译服务。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/tool-calls/spring-ai-alibaba-starter-tool-calling-googletranslate",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-tool-calling-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-tool-calling-googletranslate</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Tool Calling",
    childrenClass: "生产效率",
    title: "百度翻译",
    desc: "提供中文及其他语言之间的翻译功能。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/tool-calls/spring-ai-alibaba-starter-tool-calling-baidutranslate",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-tool-calling-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-tool-calling-baidutranslate</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Tool Calling",
    childrenClass: "生产效率",
    title: "有道翻译",
    desc: "支持多语言之间的翻译服务。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/tool-calls/spring-ai-alibaba-starter-tool-calling-youdaotranslate",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-tool-calling-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-tool-calling-youdaotranslate</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Tool Calling",
    childrenClass: "生产效率",
    title: "飞书",
    desc: "Lark办公套件，进行消息发送、文件管理等操作。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/tool-calls/spring-ai-alibaba-starter-tool-calling-larksuite",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-tool-calling-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-tool-calling-larksuite</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Tool Calling",
    childrenClass: "生产效率",
    title: "语雀",
    desc: "支持文档创建、管理等操作。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/tool-calls/spring-ai-alibaba-starter-tool-calling-yuque",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-tool-calling-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-tool-calling-yuque</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Tool Calling",
    childrenClass: "生产效率",
    title: "钉钉",
    desc: "支持消息发送、企业内部通讯等功能。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/tool-calls/spring-ai-alibaba-starter-tool-calling-dingtalk",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-tool-calling-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-tool-calling-dingtalk</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Tool Calling",
    childrenClass: "生产效率",
    title: "github",
    desc: "集成 GitHub API，支持代码仓库查询、问题跟踪等功能。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/tool-calls/spring-ai-alibaba-starter-tool-calling-githubtoolkit",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-tool-calling-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-tool-calling-githubtoolkit</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Tool Calling",
    childrenClass: "网页浏览",
    title: "Crawler爬虫",
    desc: "爬虫工具，支持网页内容抓取和数据采集。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/tool-calls/spring-ai-alibaba-starter-tool-calling-crawler",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-tool-calling-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-tool-calling-crawler</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Tool Calling",
    childrenClass: "网页浏览",
    title: "新浪新闻",
    desc: "新闻搜索、获取最新新闻等功能。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/tool-calls/spring-ai-alibaba-starter-tool-calling-sinanews",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-tool-calling-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-tool-calling-sinanews</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Tool Calling",
    childrenClass: "网页浏览",
    title: "今日头条",
    desc: "获取新闻数据和内容。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/tool-calls/spring-ai-alibaba-starter-tool-calling-toutiaonews",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-tool-calling-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-tool-calling-toutiaonews</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Tool Calling",
    childrenClass: "生活服务",
    title: "高德地图",
    desc: "地理位置查询、路线规划等功能。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/tool-calls/spring-ai-alibaba-starter-tool-calling-amap",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-tool-calling-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-tool-calling-amap</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Tool Calling",
    childrenClass: "生活服务",
    title: "百度地图",
    desc: "地理位置查询、路线规划等功能。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/tool-calls/spring-ai-alibaba-starter-tool-calling-baidumap",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-tool-calling-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-tool-calling-baidumap</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Tool Calling",
    childrenClass: "生活服务",
    title: "天气预报",
    desc: "天气查询功能，获取实时天气预报信息。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/tool-calls/spring-ai-alibaba-starter-tool-calling-weather",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-tool-calling-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-tool-calling-weather</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Tool Calling",
    childrenClass: "其他",
    title: "正则表达式",
    desc: "用于文本模式匹配和数据提取。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/tool-calls/spring-ai-alibaba-starter-tool-calling-regex",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-tool-calling-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-tool-calling-regex</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Tool Calling",
    childrenClass: "其他",
    title: "时间工具",
    desc: "提供当前时间和日期的获取功能，支持多种格式。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/tool-calls/spring-ai-alibaba-starter-tool-calling-time",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-tool-calling-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-tool-calling-time</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Tool Calling",
    childrenClass: "其他",
    title: "JSON解析",
    desc: "提供JSON数据处理功能，用于JSON数据的解析、修改等操作。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/tool-calls/spring-ai-alibaba-starter-tool-calling-jsonprocessor",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-tool-calling-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-tool-calling-jsonprocessor</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  // ========= Vector Store =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Vector Store",
    childrenClass: "全部",
    title: "OpenSearch",
    desc: "阿里云OpenSearch向量检索版适配，支持全文搜索和实时分析。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/vector-stores/spring-ai-alibaba-starter-opensearch-store",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-rag-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-opensearch-store</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Vector Store",
    childrenClass: "全部",
    title: "AnalyticDB",
    desc: "云原生数据仓库AnalyticDB PostgreSQL版的向量数据库",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/vector-stores/spring-ai-alibaba-starter-analyticdb-store",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-rag-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-analyticdb-store</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Vector Store",
    childrenClass: "全部",
    title: "Tair",
    desc: "阿里云自研TairVector提供高性能、实时，集存储、检索于一体的向量数据库服务。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/vector-stores/spring-ai-alibaba-starter-tair-store",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-rag-example",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter-tair-store</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Vector Store",
    childrenClass: "全部",
    title: "Redis",
    desc: "Redis Search and Query extends the core features of Redis OSS and allows you to use Redis as a vector database.",
    link: "https://github.com/spring-projects/spring-ai/tree/main/vector-stores/spring-ai-redis-store",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-rag-example",
    rely: "<dependency>\n  <groupId>org.springframework.ai</groupId>\n  <artifactId>spring-ai-redis-store</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Vector Store",
    childrenClass: "全部",
    title: "ElasticSearch",
    desc: "Elasticsearch is an open source search and analytics engine based on the Apache Lucene library.",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/vector-stores/spring-ai-elasticsearch-store",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-rag-example",
    rely: "<dependency>\n  <groupId>org.springframework.ai</groupId>\n  <artifactId>spring-ai-elasticsearch-store</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Vector Store",
    childrenClass: "全部",
    title: "milvus",
    desc: "Milvus is an open-source vector database",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/vector-stores/spring-ai-milvus-store",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-rag-example/rag-milvus-example",
    rely: "<dependency>\n  <groupId>org.springframework.ai</groupId>\n  <artifactId>spring-ai-milvus-store</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Vector Store",
    childrenClass: "全部",
    title: "PGvector",
    desc: "PGvector is an open-source extension for PostgreSQL that enables storing and searching over machine learning-generated embeddings.",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/vector-stores/spring-ai-pgvector-store",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-rag-example/rag-pgvector-example",
    rely: "<dependency>\n  <groupId>org.springframework.ai</groupId>\n  <artifactId>spring-ai-pgvector-store</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  // ========= Memory =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Memory",
    childrenClass: "全部",
    title: "InMemory",
    desc: "ChatMemory 多轮会话存储实现，内存存储，适用于短期会话。",
    link: "内置支持",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-chat-memory-example",
    rely: "内置支持",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Memory",
    childrenClass: "全部",
    title: "Redis",
    desc: "基于 Redis 的 ChatMemory 多轮会话存储实现。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/memories/spring-ai-alibaba-redis-memory",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-chat-memory-example",
    rely: "<dependency>\n" +
        "  <groupId>com.alibaba.cloud.ai</groupId>\n" +
        "  <artifactId>spring-ai-alibaba-redis-memory</artifactId>\n" +
        "  <version>${version}</version>\n" +
        "</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Memory",
    childrenClass: "全部",
    title: "Mysql",
    desc: "基于 Mysql 的 ChatMemory 多轮会话存储实现。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/memories/spring-ai-alibaba-mysql-memory",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-chat-memory-example",
    rely: "<dependency>\n" +
        "  <groupId>com.alibaba.cloud.ai</groupId>\n" +
        "  <artifactId>spring-ai-alibaba-mysql-memory</artifactId>\n" +
        "  <version>${version}</version>\n" +
        "</dependency>",
  },
  // ========= Document Reader =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Document Reader",
    childrenClass: "数据格式",
    title: "PDF",
    desc: "支持 PDF 格式的文档内容解析与读取。",
    link: "https://github.com/spring-projects/spring-ai/tree/main/document-readers/pdf-reader",
    example: "",
    rely: "<dependency>\n" +
        "  <groupId>org.springframework.ai</groupId>\n" +
        "  <artifactId>spring-ai-pdf-document-reader</artifactId>\n" +
        "  <version>${version}</version>\n" +
        "</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Document Reader",
    childrenClass: "数据格式",
    title: "Tika",
    desc: "支持各种格式的文档读取，包括pdf、txt、图像、word文档等。",
    link: "https://github.com/spring-projects/spring-ai/tree/main/document-readers/tika-reader",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-text-summarizer-example",
    rely: "<dependency>\n" +
        "  <groupId>org.springframework.ai</groupId>\n" +
        "  <artifactId>spring-ai-tika-document-reader</artifactId>\n" +
        "  <version>${version}</version>\n" +
        "</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Document Reader",
    childrenClass: "数据格式",
    title: "POI",
    desc: "基于 Mysql 的 ChatMemory 多轮会话存储实现。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/memories/spring-ai-alibaba-mysql-memory",
    example: "",
    rely: "<dependency>\n" +
        "  <groupId>com.alibaba.cloud.ai</groupId>\n" +
        "  <artifactId>spring-ai-alibaba-mysql-memory</artifactId>\n" +
        "  <version>${version}</version>\n" +
        "</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "Document Reader",
    childrenClass: "数据来源",
    title: "Mysql",
    desc: "基于 Mysql 的 ChatMemory 多轮会话存储实现。",
    link: "https://github.com/alibaba/spring-ai-alibaba/tree/main/community/memories/spring-ai-alibaba-mysql-memory",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-chat-memory-example",
    rely: "<dependency>\n" +
        "  <groupId>com.alibaba.cloud.ai</groupId>\n" +
        "  <artifactId>spring-ai-alibaba-mysql-memory</artifactId>\n" +
        "  <version>${version}</version>\n" +
        "</dependency>",
  },
  // ========= LLM =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "LLM",
    childrenClass: "ChatClient",
    title: "Dashscope",
    desc: "基于阿里通义系列模型适配，支持 qwen-max 等文本对话。",
    link: "http://java2ai.com/docs/1.0.0-M6.1/models/dashscope/",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-chat-example/deepseek-chat",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "LLM",
    childrenClass: "ChatClient",
    title: "OpenAI",
    desc: "基于 OpenAI 模型适配，支持文本对话。",
    link: "http://java2ai.com/docs/1.0.0-M6.1/models/openAI/",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-chat-example/openai-chat",
    rely: "<dependency>\n  <groupId>org.springframework.ai</groupId>\n  <artifactId>spring-ai-openai-spring-boot-starter</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "LLM",
    childrenClass: "ChatClient",
    title: "DeepSeek",
    desc: "基于阿里通义模型适配，支持 deepseek-r1 等文本模型。",
    link: "http://java2ai.com/docs/1.0.0-M6.1/models/deepseek/",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-chat-example/deepseek-chat",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "LLM",
    childrenClass: "ChatClient",
    title: "QwQ 32B",
    desc: "基于阿里通义模型适配，支持 qwq-32b 开源文本模型。",
    link: "http://java2ai.com/docs/1.0.0-M6.1/models/qwq/",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-chat-example/qwq-chat",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "LLM",
    childrenClass: "ChatClient",
    title: "Ollama",
    desc: "通过Spring AI官方对OpenAI的适配，支持Ollama等本地模型接入。",
    link: "http://java2ai.com/docs/1.0.0-M6.1/models/like-openAI/",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-chat-example/ollama-chat",
    rely: "<dependency>\n  <groupId>org.springframework.ai</groupId>\n  <artifactId>spring-ai-openai-spring-boot-starter</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "LLM",
    childrenClass: "ImageModel",
    title: "Dashscope",
    desc: "基于阿里通义系列模型适配，支持文字描述生成图片。",
    link: "http://java2ai.com/docs/1.0.0-M6.1/tutorials/chat-model/?spm=5176.29160081.0.0.205b1910lYIZpZ#image-model",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-image-example/dashscope-image",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "LLM",
    childrenClass: "ImageModel",
    title: "OpenAI",
    desc: "基于OpenAI系列模型适配，支持文字描述生成图片。",
    link: "https://docs.spring.io/spring-ai/reference/api/image/openai-image.html",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-image-example/openai-image",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "LLM",
    childrenClass: "AudioModel",
    title: "Dashscope",
    desc: "阿里百炼语音模式适配，支持文字生成语音（TTS）、语音生成文字（Transcription）等功能。",
    link: "http://java2ai.com/docs/1.0.0-M6.1/tutorials/chat-model/?spm=5176.29160081.0.0.205b1910lYIZpZ#audio-model",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-audio-example/dashscope-audio",
    rely: "<dependency>\n  <groupId>com.alibaba.cloud.ai</groupId>\n  <artifactId>spring-ai-alibaba-starter</artifactId>\n  <version>${version}</version>\n</dependency>",
  },
];


