# 计划轮询配置
manus:
  plan:
    polling:
      # 是否启用轮询
      enable-polling: true
      # 最大轮询次数
      max-attempts: 60
      # 轮询间隔（毫秒）
      poll-interval: 2000
      # 连接超时时间（毫秒）
      connect-timeout: 5000
      # 读取超时时间（毫秒）
      read-timeout: 10000
      # 指数退避基础延迟（毫秒）
      base-backoff-delay: 1000
      # 最大退避延迟（毫秒）
      max-backoff-delay: 10000
