title = "Gitleaks Config"

[[allowlists]]
description = "Ignore known false positives and non-sensitive files"
paths = [
    "spring-ai-alibaba-studio/spring-ai-alibaba-studio-server/docker/middleware/docker-compose.yaml",
    "spring-ai-alibaba-studio/spring-ai-alibaba-studio-server/spring-ai-alibaba-studio-server-admin/src/main/resources/static/3088.async.js",
    "spring-ai-alibaba-studio/spring-ai-alibaba-studio-server/spring-ai-alibaba-studio-server-admin/src/main/resources/static/p__Setting__ModelService__index.async.js",
    "spring-ai-alibaba-studio/spring-ai-alibaba-studio-server/spring-ai-alibaba-studio-server-core/src/main/java/com/alibaba/cloud/ai/studio/core/utils/security/RSACryptUtils.java",
    "spring-ai-alibaba-studio/spring-ai-alibaba-studio-server/spring-ai-alibaba-studio-server-admin/src/main/resources/static/2782.async.js",
    "spring-ai-alibaba-studio/spring-ai-alibaba-studio-server/spring-ai-alibaba-studio-server-core/src/main/resources/keys/private.pem",
    "spring-ai-alibaba-studio/spring-ai-alibaba-studio-server/spring-ai-alibaba-studio-server-admin/src/main/resources/static/p__App__Workflow__index.async.js",
    "spring-ai-alibaba-studio/spring-ai-alibaba-studio-server/spring-ai-alibaba-studio-server-admin/src/main/resources/static/6651.async.js"
]
