spring:
  application:
    name: cli-debug-example
  threads:
    virtual:
      enabled: true
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

