spring:
  application:
    name: cli-debug-example

  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}

server:
  port: 8080

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

#logging:
#  pattern:
#    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]