site:
  name: Spring AI Alibaba
  site: 'https://java2ai.com'
  base: '/'
  trailingSlash: 'always'
  websiteGithubUrl: 'https://github.com/springaialibaba/spring-ai-alibaba-website/blob/main'
  githubUrl: 'https://github.com/springaialibaba/spring-ai-alibaba-website'
  logoUrl: '/saa_logo.png'
  downloadEbooks: 'https://developer.aliyun.com/ebook/7565'

analytics:
  vendors:
    googleAnalytics:
      id: 'G-NP3B57ZGEF'  # or "G-XXXXXXXXXX"
    baiduAnalytics:
      id: '0b8bbee27b5404c869dded46a59bdc8d'
      verification: 'code-wzq5sw7io3'
    aesAnalytics:
      pid: 'b3kPns'
    clarityAlalytics:
      id: 'l4jzj6wbhh'

# Default SEO metadata
metadata:
  title:
    default: 'AstroWind'
    template: '%s — AstroWind'
  description: "🚀 Suitable for Startups, Small Business, Sass Websites, Professional Portfolios, Marketing Websites, Landing Pages & Blogs."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 'AstroWind'
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: 'website'
  twitter:
    handle: '@onwidget'
    site: '@onwidget'
    cardType: 'summary_large_image'

ui:
  colors:
    # Primary button color, usually the medium tone of the main color
    primary: '#5DC07E'  # green-08
    # Secondary button color, usually the lightest shade of gray
    secondary: '#F6F8F8'  # moss-01
    # Accent color, used for "Contact Us" in the header
    accent: '#418B47'  # green-10
    # Neutral color, used for large headline text
    neutral: '#0C1D0D'  # green-14
    # Base color, used as background color 1 on the homepage
    base-100: '#F6F8F8'  # moss-01
    # Info color, used for small text above headlines and footer trademark text
    info: '#666963'  # gray-10
    # Success color, used for header separators and section dividers in features or feedback
    success: '#7E9B99'  # moss-08
    # Warning color, used for toggle-trigger-atc in the header
    warning: '#597371'  # moss-10
    # Error color, used as background for components like search
    error: '#EBEFEF'  # moss-02
    # Muted background color, used for isLight mode in companies feedback
    muted: '#D3EDD5'  # green-03
    # Text color for search/language switch components
    link: '#DDE4E4'  # moss-03
