const KEY_PREFIX = "__PROVIDE_INJECT_KEY_";

export const PROVIDE_INJECT_KEY = {
  LOCALE: KEY_PREFIX + "LOCALE",
  SEARCH_DOMAIN: KEY_PREFIX + "SEARCH_DOMAIN",
  COLLAPSED: KEY_PREFIX + "COLLAPSED",
};
