spring:
  application:
    name: spring-ai-alibaba-studio
  ai:
    dashscope:
      api-key: sk-fe3978a15ee242b4b4ae399c7096f392
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
    map-underscore-to-camel-case: true
server:
  port: 8080
