spring:
  application:
    name: function-calling-example

  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}


plugins:
  dingTalk:
    customRobot:
      accessToken: ${plugins.dingTalk.customRobot.customRobot.accessToken} # accessToken of custom robot
      signature: ${plugins.dingTalk.customRobot.customRobot.signature}     # sign of custom robot