spring:
  application:
    name: function-calling-example

  ai:
    dashscope:
      api-key:  sk-3100cdd1bf0c43aa877e0c3ad56dd369
    alibaba:
      plugin:
        dingtalk:
          enabled: true
          custom-robot-access-token: ${DingTalk_Custom_Robot_Access_Token} # accessToken of custom robot
          custom-robot-signature: ${DingTalk_Custom_Robot_Signature}     # sign of custom robot
        bing:
          enabled: true
          token: ${AI_BING_TOKEN}
        gaode:
          enabled: true
          web-api-key: ${GaoDe_Web_API_Key}
        weather:
          api-key: ${AI_WEATHER_API_KEY}

