spring:
  application:
    name: function-calling-example

  ai:
    dashscope:
      api-key:  ${AI_DASHSCOPE_API_KEY}
    alibaba:
      plugin:
        dingtalk:
          enabled: true
          custom-robot:
            access-token: ${spring.ai.alibaba.plugin.ding-talk.custom-robot.access-token} # accessToken of custom robot
            signature: ${spring.ai.alibaba.plugin.ding-talk.custom-robot.signature}     # sign of custom robot

