spring:
  application:
    name: cfunction-calling-example

  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
    alibaba:
      plugin:
        bing:
          enabled: true
          token: ${AI_BING_TOKEN}