spring:
  application:
    name: crawler-plugin-example

  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}

    alibaba:
      plugin:
        crawler:
          jina:
            enabled: true
            token: ${JINA_TOKEN}
          firecrawl:
            enabled: true
            token: ${FIRECRAWL_TOKEN}
            formats: markdown, html

logging:
    level:
        com.alibaba.cloud.ai.plugin.crawler: DEBUG
