package com.alibaba.cloud.ai.memory.jdbc;

import java.sql.Connection;

/**
 * @author future0923
 */
public class OracleChatMemory extends JdbcChatMemory{

    private static final String JDBC_TYPE = "oracle";

    public OracleChatMemory(String username, String password, String url) {
        super(username, password, url);
    }

    public OracleChatMemory(String username, String password, String url, String tableName) {
        super(username, password, url, tableName);
    }

    public OracleChatMemory(Connection connection) {
        super(connection);
    }

    public OracleChatMemory(Connection connection, String tableName) {
        super(connection, tableName);
    }

    @Override
    protected String jdbcType() {
        return JDBC_TYPE;
    }

    @Override
    protected String hasTableSql(String tableName) {
        return String.format("SELECT table_name FROM user_tables WHERE table_name = '%s'", tableName.toUpperCase());
    }

    @Override
    protected String createTableSql(String tableName) {
        return String.format("CREATE TABLE %s ( id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, conversation_id VARCHAR2(256), messages CLOB, CONSTRAINT uniq_conversation_id UNIQUE (conversation_id));", tableName);
    }
}
