export const pluginEmums = [
  // ========= MCP  浏览器自动化=========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "浏览器自动化",
    childrenClass: "全部",
    title: "playwright-plus-python-mcp",
    desc: "使用 Playwright 进行浏览器自动化的 MCP 服务器，更适合llm",
    link: "https://github.com/blackwhite084/playwright-plus-python-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "{\n" +
        "  \"mcpServers\": {\n" +
        "    \"playwright\": {\n" +
        "      \"command\": \"npx\",\n" +
        "      \"args\": [\"-y\", \"@executeautomation/playwright-mcp-server\"]\n" +
        "    }\n" +
        "  }\n" +
        "}",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "浏览器自动化",
    childrenClass: "全部",
    title: "playwright-mcp-server",
    desc: "使用 Playwright 进行浏览器自动化和网页抓取的 MCP 服务器",
    link: "https://github.com/executeautomation/mcp-playwright",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "浏览器自动化",
    childrenClass: "全部",
    title: "mcp-server-playwright",
    desc: "使用 Playwright 实现浏览器自动化的 MCP 服务器",
    link: "https://github.com/Automata-Labs-team/MCP-Server-Playwright",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "浏览器自动化",
    childrenClass: "全部",
    title: "server-puppeteer",
    desc: "用于网页抓取和交互的浏览器自动化",
    link: "https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "浏览器自动化",
    childrenClass: "全部",
    title: "mcp-server-youtube-transcript",
    desc: "获取 YouTube 字幕和文字记录以供 AI 分析",
    link: "https://github.com/kimtaeyoon83/mcp-server-youtube-transcript",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "浏览器自动化",
    childrenClass: "全部",
    title: "mcp-server-apple-shortcuts",
    desc: "MCP 服务器与 Apple Shortcuts 的集成",
    link: "https://github.com/recursechat/mcp-server-apple-shortcuts",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "浏览器自动化",
    childrenClass: "全部",
    title: "mcp-server-apple-reminders",
    desc: "macOS 上与 Apple Reminders 集成的 MCP 服务器",
    link: "https://github.com/FradSer/mcp-server-apple-reminders",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "浏览器自动化",
    childrenClass: "全部",
    title: "mcp-aoai-web-browsing",
    desc: "使用 Azure OpenAI 和 Playwright 的\"最小\"服务器/客户端 MCP 实现",
    link: "https://github.com/kimtth/mcp-aoai-web-browsing",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "浏览器自动化",
    childrenClass: "全部",
    title: "web-search",
    desc: "一个支持使用 Google 搜索结果进行免费网页搜索的 MCP 服务器，无需 API 密钥",
    link: "https://github.com/pskill9/web-search",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "浏览器自动化",
    childrenClass: "全部",
    title: "browser-use-mcp-server",
    desc: "browser-use是一个封装了SSE传输协议的MCP服务器。包含一个dockerfile用于在docker中运行chromium浏览器+VNC服务器",
    link: "https://github.com/co-browser/browser-use-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "浏览器自动化",
    childrenClass: "全部",
    title: "bilibili-mcp-js",
    desc: "一个支持搜索 B站 内容的 MCP 服务器。提供LangChain调用示例、测试脚本",
    link: "https://github.com/34892002/bilibili-mcp-js",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "浏览器自动化",
    childrenClass: "全部",
    title: "ashra-mcp",
    desc: "从任何网站提取结构化数据。只需输入提示即可获取JSON",
    link: "https://github.com/getrupt/ashra-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 艺术与文化 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "艺术与文化",
    childrenClass: "全部",
    title: "video-editing-mcp",
    desc: "从您的视频集合中添加、分析、搜索和生成视频剪辑",
    link: "https://github.com/burningion/video-editing-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "艺术与文化",
    childrenClass: "全部",
    title: "rijksmuseum-mcp",
    desc: "荷兰国立博物馆 API 集成，支持艺术品搜索、详情查询和收藏品浏览",
    link: "https://github.com/r-huijts/rijksmuseum-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "艺术与文化",
    childrenClass: "全部",
    title: "anilist-mcp",
    desc: "集成 AniList API 获取动画和漫画信息的 MCP 服务器",
    link: "https://github.com/yuna0x0/anilist-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 云平台 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "云平台",
    childrenClass: "全部",
    title: "mcp-server-cloudflare",
    desc: "与 Cloudflare 服务集成，包括 Workers、KV、R2 和 D1",
    link: "https://github.com/cloudflare/mcp-server-cloudflare",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "云平台",
    childrenClass: "全部",
    title: "aws-mcp-server",
    desc: "一款轻量但功能强大的服务器，使AI助手能够在支持多架构的安全Docker环境中执行AWS CLI命令、使用Unix管道，并为常见AWS任务应用提示模板",
    link: "https://github.com/alexei-led/aws-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "云平台",
    childrenClass: "全部",
    title: "mcp-k8s-go",
    desc: "通过 MCP 操作 Kubernetes 集群",
    link: "https://github.com/strowk/mcp-k8s-go",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "云平台",
    childrenClass: "全部",
    title: "mcp-server-kubernetes",
    desc: "使用 Typescript 实现 Kubernetes 集群中针对 pod、部署、服务的操作",
    link: "https://github.com/Flux159/mcp-server-kubernetes",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "云平台",
    childrenClass: "全部",
    title: "kubernetes-mcp-server",
    desc: "一个功能强大的Kubernetes MCP服务器，额外支持OpenShift。除了为任何Kubernetes资源提供CRUD操作外，该服务器还提供专用工具与您的集群进行交互",
    link: "https://github.com/manusa/kubernetes-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "云平台",
    childrenClass: "全部",
    title: "mcp-k8s-eye",
    desc: "提供 Kubernetes 集群资源管理, 深度分析集群和应用的健康状态",
    link: "https://github.com/wenhuwang/mcp-k8s-eye",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "云平台",
    childrenClass: "全部",
    title: "netskope-mcp",
    desc: "提供对 Netskope Private Access 环境中所有组件的访问权限，包含详细的设置信息和 LLM 使用示例",
    link: "https://github.com/johnneerdael/netskope-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "云平台",
    childrenClass: "全部",
    title: "tfmcp",
    desc: "一个Terraform MCP服务器，允许AI助手管理和操作Terraform环境，实现读取配置、分析计划、应用配置以及管理Terraform状态的功能",
    link: "https://github.com/nwiizo/tfmcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "云平台",
    childrenClass: "全部",
    title: "esxi-mcp-server",
    desc: "提供对 VMware ESXi/vCenter 管理服务器，提供简单的 REST API 接口来管理虚拟机",
    link: "https://github.com/bright8192/esxi-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "云平台",
    childrenClass: "全部",
    title: "k8m",
    desc: "提供MCP多集群k8s管理操作，提供管理界面、日志，内置近50种工具，覆盖常见运维开发场景，支持常规资源、CRD资源",
    link: "https://github.com/weibaohui/k8m",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 命令行 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "命令行",
    childrenClass: "全部",
    title: "iterm-mcp",
    desc: "一个为 iTerm 终端提供访问能力的 MCP 服务器。您可以执行命令，并就终端中看到的内容进行提问交互",
    link: "https://github.com/ferrislucas/iterm-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "命令行",
    childrenClass: "全部",
    title: "mcp-server-commands",
    desc: "使用`run_command`和`run_script`工具运行任何命令",
    link: "https://github.com/g0t4/mcp-server-commands",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "命令行",
    childrenClass: "全部",
    title: "cli-mcp-server",
    desc: "具有安全执行和可定制安全策略的命令行界面",
    link: "https://github.com/MladenSU/cli-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "命令行",
    childrenClass: "全部",
    title: "mcp-shell-server",
    desc: "实现模型上下文协议 (MCP) 的安全 shell 命令执行服务器",
    link: "https://github.com/tumf/mcp-shell-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 社交 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社交",
    childrenClass: "全部",
    title: "gtasks-mcp",
    desc: "用于管理 Google Tasks 的 MCP 服务器",
    link: "https://github.com/zcaceres/gtasks-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社交",
    childrenClass: "全部",
    title: "imessage-query-fastmcp-mcp-server",
    desc: "MCP 服务器通过模型上下文协议 (MCP) 提供对 iMessage 数据库的安全访问，使 LLM 能够通过适当的电话号码验证和附件处理来查询和分析 iMessage 对话",
    link: "https://github.com/hannesrudolph/imessage-query-fastmcp-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社交",
    childrenClass: "全部",
    title: "server-slack",
    desc: "用于频道管理和消息传递的 Slack 工作区集成",
    link: "https://github.com/modelcontextprotocol/servers/tree/main/src/slack",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 客户数据平台 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "客户数据平台",
    childrenClass: "全部",
    title: "inoyu-mcp-unomi-server",
    desc: "MCP 服务器用于访问和更新 Apache Unomi CDP 服务器上的配置文件",
    link: "https://github.com/sergehuber/inoyu-mcp-unomi-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "客户数据平台",
    childrenClass: "全部",
    title: "OpenDataMCP",
    desc: "使用模型上下文协议将任何开放数据连接到任何 LLM",
    link: "https://github.com/OpenDataMCP/OpenDataMCP",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "客户数据平台",
    childrenClass: "全部",
    title: "mcp-tinybird",
    desc: "MCP 服务器可从任何 MCP 客户端与 Tinybird Workspace 进行交互",
    link: "https://github.com/tinybirdco/mcp-tinybird",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "客户数据平台",
    childrenClass: "全部",
    title: "mcp-server-iaptic",
    desc: "连接 iaptic 平台，让您轻松查询客户购买记录、交易数据以及应用营收统计信息",
    link: "https://github.com/iaptic/mcp-server-iaptic",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 数据库 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "数据库",
    childrenClass: "全部",
    title: "alibabacloud-tablestore-mcp-server",
    desc: "阿里云表格存储(Tablestore)的 MCP 服务器实现，特性包括添加文档、基于向量和标量进行语义搜索、RAG友好",
    link: "https://github.com/aliyun/alibabacloud-tablestore-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "数据库",
    childrenClass: "全部",
    title: "elasticsearch-mcp-server",
    desc: "集成 Elasticsearch 的 MCP 服务器实现",
    link: "https://github.com/cr7258/elasticsearch-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "数据库",
    childrenClass: "全部",
    title: "airtable-mcp-server",
    desc: "Airtable 数据库集成，具有架构检查、读写功能",
    link: "https://github.com/domdomegg/airtable-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "数据库",
    childrenClass: "全部",
    title: "airtable-mcp",
    desc: "将AI工具直接连接至Airtable。通过自然语言查询、创建、更新及删除记录",
    link: "https://github.com/rashidazarang/airtable-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "数据库",
    childrenClass: "全部",
    title: "mcp-server-bigquery",
    desc: "BigQuery 数据库集成了架构检查和查询功能",
    link: "https://github.com/LucasHild/mcp-server-bigquery",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "数据库",
    childrenClass: "全部",
    title: "mcp-server-tidb",
    desc: "TiDB 数据库集成，包括表结构的建立 DDL 和 SQL 的执行",
    link: "https://github.com/c4pt0r/mcp-server-tidb",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "数据库",
    childrenClass: "全部",
    title: "dolphindb-mcp-server",
    desc: "DolphinDB数据库集成，具备模式检查与查询功能",
    link: "https://github.com/tradercjz/dolphindb-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "数据库",
    childrenClass: "全部",
    title: "mcp-bigquery-server",
    desc: "Google BigQuery 集成的服务器实现，可实现直接 BigQuery 数据库访问和查询功能",
    link: "https://github.com/ergut/mcp-bigquery-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "数据库",
    childrenClass: "全部",
    title: "mcp-clickhouse",
    desc: "集成 Apache Kafka 和 Timeplus。可以获取Kafka中的最新数据，并通过 Timeplus 来 SQL 查询",
    link: "https://github.com/ClickHouse/mcp-clickhouse",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "数据库",
    childrenClass: "全部",
    title: "firebase-mcp",
    desc: "包括认证、Firestore和存储在内的Firebase服务",
    link: "https://github.com/gannonh/firebase-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "数据库",
    childrenClass: "全部",
    title: "mcp-timeplus",
    desc: "用于Apache Kafka和Timeplus的MCP服务器。能够列出Kafka主题、轮询Kafka消息、将Kafka数据本地保存，并通过Timeplus使用SQL查询流数据",
    link: "https://github.com/jovezhong/mcp-timeplus",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "数据库",
    childrenClass: "全部",
    title: "mcp-database-server",
    desc: "Fireproof 分布式账本数据库，支持多用户数据同步",
    link: "https://github.com/fireproof-storage/mcp-database-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "数据库",
    childrenClass: "全部",
    title: "mysql_mcp_server",
    desc: "MySQL 数据库集成可配置的访问控制、模式检查和全面的安全指南",
    link: "https://github.com/designcomputer/mysql_mcp_server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "数据库",
    childrenClass: "全部",
    title: "mcp-mysql-server",
    desc: "基于 Node.js 的 MySQL 数据库集成，提供安全的 MySQL 数据库操作",
    link: "https://github.com/f4ww4z/mcp-mysql-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "数据库",
    childrenClass: "全部",
    title: "db-mcp-server",
    desc: "一款基于Golang构建的高性能多数据库MCP服务器，支持MySQL和PostgreSQL（即将支持NoSQL）",
    link: "https://github.com/FreePeak/db-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 开发者工具 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "开发者工具",
    childrenClass: "全部",
    title: "Magic-MCP",
    desc: "打造受21世纪顶尖设计工程师启发的精致UI组件",
    link: "https://github.com/21st-dev/magic-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "开发者工具",
    childrenClass: "全部",
    title: "Opik-MCP",
    desc: "使用自然语言与您的LLM可观测性、Opik捕获的追踪和监控数据进行对话",
    link: "https://github.com/comet-ml/opik-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "开发者工具",
    childrenClass: "全部",
    title: "Figma-Context-MCP",
    desc: "为编码代理提供直接访问Figma数据的权限，助力其一次性完成设计实现",
    link: "https://github.com/GLips/Figma-Context-MCP",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "开发者工具",
    childrenClass: "全部",
    title: "docker-mcp",
    desc: "通过 MCP 进行 Docker 容器管理和操作",
    link: "https://github.com/QuantGeekDev/docker-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "开发者工具",
    childrenClass: "全部",
    title: "fetch-mcp",
    desc: "一个灵活获取 JSON、文本和 HTML 数据的 MCP 服务器",
    link: "https://github.com/zcaceres/fetch-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "开发者工具",
    childrenClass: "全部",
    title: "xcode-mcp-server",
    desc: "Xcode 集成，支持项目管理、文件操作和构建自动化",
    link: "https://github.com/r-huijts/xcode-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 数据科学工具 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "数据科学工具",
    childrenClass: "全部",
    title: "mcp-server-data-exploration",
    desc: "支持对基于 .csv 的数据集进行自主数据探索，以最小的成本提供智能见解",
    link: "https://github.com/reading-plus-ai/mcp-server-data-exploration",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "数据科学工具",
    childrenClass: "全部",
    title: "markdownify-mcp",
    desc: "一个 MCP 服务器，可将几乎任何文件或网络内容转换为 Markdown",
    link: "https://github.com/zcaceres/markdownify-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 文件系统 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "文件系统",
    childrenClass: "全部",
    title: "server-filesystem",
    desc: "直接访问本地文件系统",
    link: "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "文件系统",
    childrenClass: "全部",
    title: "server-google-drive",
    desc: "Google Drive 集成，用于列出、阅读和搜索文件",
    link: "https://github.com/modelcontextprotocol/servers/tree/main/src/gdrive",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "文件系统",
    childrenClass: "全部",
    title: "box-mcp-server",
    desc: "Box 集成，支持文件列表、阅读和搜索功能",
    link: "https://github.com/hmk/box-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "文件系统",
    childrenClass: "全部",
    title: "mcp-filesystem-server",
    desc: "用于本地文件系统访问的 Golang 实现",
    link: "https://github.com/mark3labs/mcp-filesystem-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 金融与金融科技 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "金融与金融科技",
    childrenClass: "全部",
    title: "heurist-mesh-mcp-server",
    desc: "通过Heurist Mesh网络访问专业化的web3 AI代理，用于区块链分析、智能合约安全审计、代币指标评估及链上交互",
    link: "https://github.com/heurist-network/heurist-mesh-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "金融与金融科技",
    childrenClass: "全部",
    title: "base-mcp",
    desc: "集成Base网络的链上工具，支持与Base网络及Coinbase API交互，实现钱包管理、资金转账、智能合约和DeFi操作",
    link: "https://github.com/base/base-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "金融与金融科技",
    childrenClass: "全部",
    title: "coincap-mcp",
    desc: "使用 CoinCap 的公共 API 集成实时加密货币市场数据，无需 API 密钥即可访问加密货币价格和市场信息",
    link: "https://github.com/QuantGeekDev/coincap-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 游戏 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "游戏",
    childrenClass: "全部",
    title: "godot-mcp",
    desc: "一个用于与Godot游戏引擎交互的MCP服务器，提供编辑、运行、调试和管理Godot项目中场景的工具",
    link: "https://github.com/Coding-Solo/godot-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "游戏",
    childrenClass: "全部",
    title: "fantasy-pl-mcp",
    desc: "用于实时 Fantasy Premier League 数据和分析工具的 MCP 服务器",
    link: "https://github.com/rishijatia/fantasy-pl-mcp/",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "游戏",
    childrenClass: "全部",
    title: "mcp-unity",
    desc: "Unity3d 游戏引擎集成 MCP 服务器",
    link: "https://github.com/CoderGamester/mcp-unity",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 知识与记忆 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "知识与记忆",
    childrenClass: "全部",
    title: "server-memory",
    desc: "基于知识图谱的长期记忆系统用于维护上下文",
    link: "https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "知识与记忆",
    childrenClass: "全部",
    title: "MemoryMesh",
    desc: "增强基于图形的记忆，重点关注 AI 角色扮演和故事生成",
    link: "https://github.com/CheMiguel23/MemoryMesh",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "知识与记忆",
    childrenClass: "全部",
    title: "cognee",
    desc: "AI应用程序和Agent的内存管理器使用各种图存储和向量存储，并允许从 30 多个数据源提取数据",
    link: "https://github.com/topoteretes/cognee/tree/dev/cognee-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 位置服务 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "位置服务",
    childrenClass: "全部",
    title: "amap-maps-mcp-server",
    desc: "高德地图集成，提供位置服务、路线规划和地点详细信息",
    link: "none",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "{\n" +
        "    \"mcpServers\": {\n" +
        "        \"amap-maps\": {\n" +
        "            \"command\": \"npx\",\n" +
        "            \"args\": [\n" +
        "                \"-y\",\n" +
        "                \"@amap/amap-maps-mcp-server\"\n" +
        "            ],\n" +
        "            \"env\": {\n" +
        "                \"AMAP_MAPS_API_KEY\": \"您在高德官网上申请的key\"\n" +
        "            }\n" +
        "        }\n" +
        "    }\n" +
        "}\n",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "位置服务",
    childrenClass: "全部",
    title: "mcp-server-baidu-map",
    desc: "百度地图集成，提供位置服务、路线规划和地点详细信息",
    link: "https://github.com/baidu-maps/mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "{\n" +
        "    \"mcpServers\": {\n" +
        "        \"baidu-map\": {\n" +
        "            \"command\": \"npx\",\n" +
        "            \"args\": [\n" +
        "                \"-y\",\n" +
        "                \"@baidumap/mcp-server-baidu-map\"\n" +
        "            ],\n" +
        "            \"env\": {\n" +
        "                \"BAIDU_MAP_API_KEY\": \"xxx\"\n" +
        "            }\n" +
        "        }\n" +
        "    }\n" +
        "}",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "位置服务",
    childrenClass: "全部",
    title: "server-google-maps",
    desc: "Google 地图集成，提供位置服务、路线规划和地点详细信息",
    link: "https://github.com/modelcontextprotocol/servers/tree/main/src/google-maps",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "位置服务",
    childrenClass: "全部",
    title: "MCP-timeserver",
    desc: "访问任意时区的时间并获取当前本地时间",
    link: "https://github.com/SecretiveShell/MCP-timeserver",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "位置服务",
    childrenClass: "全部",
    title: "MCP-Geo",
    desc: "支持 nominatim、ArcGIS、Bing 的地理编码 MCP 服务器",
    link: "https://github.com/webcoderz/MCP-Geo",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 营销 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "营销",
    childrenClass: "全部",
    title: "osp_marketing_tools",
    desc: "Open Strategy Partners 提供的营销工具套件，包含写作风格指南、编辑规范和产品营销价值图谱创建工具",
    link: "https://github.com/open-strategy-partners/osp_marketing_tools",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 监测 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "监测",
    childrenClass: "全部",
    title: "server-sentry",
    desc: "Sentry.io 集成用于错误跟踪和性能监控",
    link: "https://github.com/modelcontextprotocol/servers/tree/main/src/sentry",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "监测",
    childrenClass: "全部",
    title: "mcp-server-raygun",
    desc: "Raygun API V3 集成用于崩溃报告和真实用户监控",
    link: "https://github.com/MindscapeHQ/mcp-server-raygun",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "监测",
    childrenClass: "全部",
    title: "metoro-mcp-server",
    desc: "查询并与 Metoro 监控的 kubernetes 环境交互",
    link: "https://github.com/metoro-io/metoro-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 搜索 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "搜索",
    childrenClass: "全部",
    title: "server-brave-search",
    desc: "使用 Brave 的搜索 API 实现网页搜索功能",
    link: "https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "搜索",
    childrenClass: "全部",
    title: "mcp-server-dumplingai",
    desc: "通过 Dumpling AI 提供的数据访问、网页抓取与文档转换 API",
    link: "https://github.com/Dumpling-AI/mcp-server-dumplingai",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "搜索",
    childrenClass: "全部",
    title: "nyt",
    desc: "使用 NYTimes API 搜索文章",
    link: "https://github.com/angheljf/nyt",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 安全 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "安全",
    childrenClass: "全部",
    title: "mcp-dnstwist",
    desc: "dnstwist 的 MCP 服务器，这是一个强大的 DNS 模糊测试工具，可帮助检测域名抢注、钓鱼和企业窃密行为",
    link: "https://github.com/BurtTheCoder/mcp-dnstwist",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "安全",
    childrenClass: "全部",
    title: "binary_ninja_mcp",
    desc: "Binary Ninja 的 MCP 服务器和桥接器。提供二进制分析和逆向工程工具",
    link: "https://github.com/Vector35/binaryninja-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "安全",
    childrenClass: "全部",
    title: "mcp-maigret",
    desc: "maigret 的 MCP 服务器，maigret 是一款强大的 OSINT 工具，可从各种公共来源收集用户帐户信息",
    link: "https://github.com/BurtTheCoder/mcp-maigret",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 体育 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "体育",
    childrenClass: "全部",
    title: "firstcycling-mcp",
    desc: "通过自然语言访问自行车比赛数据、结果和统计信息。功能包括从 firstcycling.com 获取参赛名单、比赛结果和车手信息",
    link: "https://github.com/r-huijts/firstcycling-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 翻译服务 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "翻译服务",
    childrenClass: "全部",
    title: "lara-mcp",
    desc: "Lara翻译API的MCP服务器，提供强大的翻译功能，支持语言检测和上下文感知翻译",
    link: "https://github.com/translated/lara-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 旅行与交通 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "旅行与交通",
    childrenClass: "全部",
    title: "mcp-server-airbnb",
    desc: "提供搜索Airbnb房源及获取详细信息的工具",
    link: "https://github.com/openbnb-org/mcp-server-airbnb",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "旅行与交通",
    childrenClass: "全部",
    title: "ns-mcp-server",
    desc: "了解荷兰铁路 (NS) 的旅行信息、时刻表和实时更新",
    link: "https://github.com/r-huijts/ns-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 版本控制 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "版本控制",
    childrenClass: "全部",
    title: "server-github",
    desc: "GitHub API集成用于仓库管理、PR、问题等",
    link: "https://github.com/modelcontextprotocol/servers/tree/main/src/github",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "版本控制",
    childrenClass: "全部",
    title: "server-gitlab",
    desc: "GitLab平台集成用于项目管理和CI/CD操作",
    link: "https://github.com/modelcontextprotocol/servers/tree/main/src/gitlab",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "版本控制",
    childrenClass: "全部",
    title: "mcp-gitee",
    desc: "Gitee API集成、仓库、问题及拉取请求管理等功能",
    link: "https://github.com/oschina/gitee",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 其他工具和集成 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "其他工具和集成",
    childrenClass: "全部",
    title: "actors-mcp-server",
    desc: "使用超过 3,000 个预构建的云工具（称为 Actors）从网站、电商、社交媒体、搜索引擎、地图等提取数据",
    link: "https://github.com/apify/actors-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "其他工具和集成",
    childrenClass: "全部",
    title: "mcp-server-calculator",
    desc: "使LLM能够使用计算器进行精确的数值计算",
    link: "https://github.com/githejie/mcp-server-calculator",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "其他工具和集成",
    childrenClass: "全部",
    title: "contentful-mcp",
    desc: "更新、创建、删除 Contentful Space 中的内容、内容模型和资产",
    link: "https://github.com/ivo-toby/contentful-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 框架 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "框架",
    childrenClass: "全部",
    title: "FastMCP-Python",
    desc: "用于在 Python 中构建 MCP 服务器的高级框架",
    link: "https://github.com/jlowin/fastmcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "框架",
    childrenClass: "全部",
    title: "FastMCP-TypeScript",
    desc: "用于在 TypeScript 中构建 MCP 服务器的高级框架",
    link: "https://github.com/punkpeye/fastmcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "框架",
    childrenClass: "全部",
    title: "Foxy-Contexts",
    desc: "用于以声明方式编写 MCP 服务器的 Golang 库，包含功能测试",
    link: "https://github.com/strowk/foxy-contexts",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 实用工具 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "实用工具",
    childrenClass: "全部",
    title: "mcp-server-and-gw",
    desc: "带有示例服务器和 MCP 客户端的 MCP stdio 到 HTTP SSE 传输网关",
    link: "https://github.com/boilingdata/mcp-server-and-gw",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "实用工具",
    childrenClass: "全部",
    title: "mcp-langchain-ts-client",
    desc: "在 LangChain.js 中使用 MCP 提供的工具",
    link: "https://github.com/isaacwasserman/mcp-langchain-ts-client",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "实用工具",
    childrenClass: "全部",
    title: "mcp-gateway",
    desc: "MCP SSE 服务器的网关演示",
    link: "https://github.com/lightconetech/mcp-gateway",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "实用工具",
    childrenClass: "全部",
    title: "mcphost",
    desc: "一个 CLI 主机应用程序，使大型语言模型 (LLM) 能够通过模型上下文协议 (MCP) 与外部工具交互",
    link: "https://github.com/mark3labs/mcphost",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "实用工具",
    childrenClass: "全部",
    title: "MCP-Connect",
    desc: "一个小工具，使基于云的 AI 服务能够通过 HTTP/HTTPS 请求访问本地的基于 Stdio 的 MCP 服务器",
    link: "https://github.com/EvalsOne/MCP-Connect",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 官方实现 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "官方实现",
    childrenClass: "全部",
    title: "Magic",
    desc: "打造受21世纪顶尖设计工程师启发的精致UI组件",
    link: "https://github.com/21st-dev/magic-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "官方实现",
    childrenClass: "全部",
    title: "Adfin",
    desc: "唯一需要的收款平台 - 所有支付集中一处，包括发票和会计对账",
    link: "https://github.com/Adfin-Engineering/mcp-server-adfin",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "官方实现",
    childrenClass: "全部",
    title: "AgentQL",
    desc: "使AI代理能够从非结构化网络中获取结构化数据",
    link: "https://github.com/tinyfish-io/agentql-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "官方实现",
    childrenClass: "全部",
    title: "AgentRPC",
    desc: "通过网络边界连接任何函数、任何语言",
    link: "https://github.com/agentrpc/agentrpc",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "官方实现",
    childrenClass: "全部",
    title: "Aiven",
    desc: "浏览Aiven项目并与PostgreSQL、Apache Kafka、ClickHouse和OpenSearch服务交互",
    link: "https://github.com/Aiven-Open/mcp-aiven",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "官方实现",
    childrenClass: "全部",
    title: "Apify Actors MCP Server",
    desc: "使用3,000+预构建的云工具从网站、电子商务、社交媒体、搜索引擎、地图等提取数据",
    link: "https://github.com/apify/actors-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "官方实现",
    childrenClass: "全部",
    title: "APIMatic MCP",
    desc: "APIMatic MCP服务器用于使用APIMatic验证OpenAPI规范",
    link: "https://github.com/apimatic/apimatic-validator-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "官方实现",
    childrenClass: "全部",
    title: "Audiense Insights",
    desc: "通过Audiense报告获取营销洞察和受众分析，包括人口统计、文化、影响者和内容参与分析",
    link: "https://github.com/AudienseCo/mcp-audiense-insights",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "官方实现",
    childrenClass: "全部",
    title: "Axiom",
    desc: "用自然语言查询和分析Axiom日志、跟踪和所有其他事件数据",
    link: "https://github.com/axiomhq/mcp-server-axiom",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "官方实现",
    childrenClass: "全部",
    title: "Bankless Onchain",
    desc: "查询链上数据，如ERC20代币、交易历史、智能合约状态",
    link: "https://github.com/bankless/onchain-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // ========= MCP 社区版实现 =========
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Ableton Live",
    desc: "一个用于控制Ableton Live的MCP服务器",
    link: "https://github.com/Simon-Kansara/ableton-live-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Airbnb",
    desc: "提供搜索Airbnb和获取房源详情的工具",
    link: "https://github.com/openbnb-org/mcp-server-airbnb",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Algorand",
    desc: "用于工具交互（40+）和资源访问（60+）的综合MCP服务器，以及许多用于与Algorand区块链交互的有用提示",
    link: "https://github.com/GoPlausible/algorand-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Airflow",
    desc: "使用官方Python客户端连接到Apache Airflow的MCP服务器",
    link: "https://github.com/yangkyeongmo/mcp-server-apache-airflow",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Airtable",
    desc: "对Airtable数据库的读写访问，具有架构检查功能",
    link: "https://github.com/domdomegg/airtable-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Airtable",
    desc: "Airtable Model Context Protocol服务器",
    link: "https://github.com/felores/airtable-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "AlphaVantage",
    desc: "股票市场数据API AlphaVantage的MCP服务器",
    link: "https://github.com/calvernaz/alphavantage",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Anki",
    desc: "一个用于与您的Anki卡片和牌组交互的MCP服务器",
    link: "https://github.com/scorzeth/anki-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Any Chat Completions",
    desc: "与任何OpenAI SDK兼容的聊天完成API交互，如OpenAI、Perplexity、Groq、xAI等",
    link: "https://github.com/pyroprompts/any-chat-completions-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Apple Calendar",
    desc: "一个MCP服务器，允许您通过自然语言与MacOS日历交互，包括事件创建、修改、日程列表、查找空闲时段等功能",
    link: "https://github.com/Omar-v2/mcp-ical",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "ArangoDB",
    desc: "通过ArangoDB提供数据库交互功能的MCP服务器",
    link: "https://github.com/ravenwits/mcp-server-arangodb",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Arduino",
    desc: "使用Claude AI和Arduino（ESP32）进行真实世界自动化和与机器人交互的AI驱动机器人技术的MCP服务器",
    link: "https://github.com/vishalmysore/choturobo",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  
  // Continuing MCP 社区版实现
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Atlassian",
    desc: "与Atlassian Cloud产品（Confluence和Jira）交互，包括搜索/阅读Confluence空间/页面、访问Jira问题和项目元数据",
    link: "https://github.com/sooperset/mcp-atlassian",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "AWS",
    desc: "使用LLM在AWS资源上执行操作",
    link: "https://github.com/rishikavikondala/mcp-server-aws",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "AWS Athena",
    desc: "用于在Glue Catalog上运行SQL查询的AWS Athena MCP服务器",
    link: "https://github.com/lishenxydlgzs/aws-athena-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "AWS Cost Explorer",
    desc: "通过检查跨区域、服务、实例类型和基础模型的支出来优化AWS支出（包括Amazon Bedrock支出）",
    link: "https://github.com/aarora79/aws-cost-explorer-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "AWS Resources Operations",
    desc: "运行生成的Python代码，安全地查询或修改boto3支持的任何AWS资源",
    link: "https://github.com/baryhuang/mcp-server-aws-resources-python",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "AWS S3",
    desc: "一个用于AWS S3的示例MCP服务器，可灵活地从S3获取对象，如PDF文档",
    link: "https://github.com/aws-samples/sample-mcp-server-s3",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Azure ADX",
    desc: "查询和分析Azure Data Explorer数据库",
    link: "https://github.com/pab1it0/adx-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Azure DevOps",
    desc: "一个MCP服务器，为Azure DevOps服务提供桥接，使AI助手能够查询和管理工作项",
    link: "https://github.com/Vortiago/mcp-azure-devops",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Baidu AI Search",
    desc: "使用百度云的AI搜索进行网络搜索",
    link: "https://github.com/baidubce/app-builder/tree/master/python/mcp_server/ai_search",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Base Free USDC Transfer",
    desc: "使用Claude AI在Base上免费发送USDC！使用Coinbase CDP构建",
    link: "https://github.com/magnetai/mcp-free-usdc-transfer",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Basic Memory",
    desc: "本地优先的知识管理系统，从Markdown文件构建语义图，实现跨LLM对话的持久记忆",
    link: "https://github.com/basicmachines-co/basic-memory",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "BigQuery",
    desc: "使LLM能够检查数据库模式并在BigQuery上执行查询",
    link: "https://github.com/LucasHild/mcp-server-bigquery",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "BigQuery",
    desc: "Google BigQuery集成的服务器实现，实现直接BigQuery数据库访问和查询功能",
    link: "https://github.com/ergut/mcp-bigquery-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Bing Web Search API",
    desc: "Microsoft Bing Web Search API的服务器实现",
    link: "https://github.com/leehanchung/bing-search-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Bitable MCP",
    desc: "MCP服务器通过模型上下文协议提供对飞书多维表格的访问，允许用户使用预定义工具与多维表格进行交互",
    link: "https://github.com/lloydzhou/bitable-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Blender",
    desc: "Blender集成允许通过提示创建、建模和操作3D场景",
    link: "https://github.com/ahujasid/blender-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Bsc-mcp",
    desc: "第一个作为AI与BNB链之间桥梁的MCP服务器，使AI代理能够通过与BNB链的无缝集成执行复杂的链上操作",
    link: "https://github.com/TermiX-official/bsc-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Calculator",
    desc: "此服务器使LLM能够使用计算器进行精确的数值计算",
    link: "https://github.com/githejie/mcp-server-calculator",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "CFBD API",
    desc: "用于College Football Data API的MCP服务器",
    link: "https://github.com/lenwood/cfbd-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "ChatMCP",
    desc: "一个开源跨平台GUI桌面应用程序，兼容Linux、macOS和Windows，通过动态可选择的LLM实现与MCP服务器的无缝交互",
    link: "https://github.com/AI-QL/chat-mcp",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "ChatSum",
    desc: "使用LLM查询和总结聊天消息",
    link: "https://github.com/mcpso/mcp-server-chatsum",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Chroma",
    desc: "基于Chroma构建的向量数据库服务器，用于语义文档搜索和元数据过滤",
    link: "https://github.com/privetin/chroma",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "ClaudePost",
    desc: "ClaudePost使Gmail的电子邮件管理变得无缝，提供安全功能如电子邮件搜索、阅读和发送",
    link: "https://github.com/ZilongXue/claude-post",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  },
  {
    img: "https://img.alicdn.com/imgextra/i1/O1CN01C4NLUr1qSJ1GED2kW_!!6000000005494-55-tps-48-48.svg",
    class: "社区版实现",
    childrenClass: "全部",
    title: "Cloudinary",
    desc: "Cloudinary模型上下文协议服务器，用于将媒体上传到Cloudinary并获取媒体链接和详细信息",
    link: "https://github.com/felores/cloudinary-mcp-server",
    example: "https://github.com/springaialibaba/spring-ai-alibaba-examples/tree/main/spring-ai-alibaba-mcp-example",
    rely: "",
  }
]
