name: Deploy to Maven Repository
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Maven Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
      - name: Deploy with Maven
        run: mvn -B deploy -DskipTests -Prelease
