# Copyright 2024-2026 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Set Issue Label and Assignee"
on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "both"
          parameters: [{"keywords": ["bug", "error"], "labels": ["kind/bug"], "assignees": ["yuluo-yx", "PolarishT"]}, {"keywords": ["help", "guidance"], "labels": ["help-wanted"], "assignees": ["yuluo-yx", "PolarishT"]}]
          github-token: "${{ secrets.GITHUB_TOKEN }}"
